### ISSUE TITLE
Change proposal: "error" channel > "response" channel

### ISSUE THREAD

**Issue by vkammerer** [joshforisha/cycle-firebase#1]
Hi @joshforisha ,

Thank you for the driver! I started a boilerplate / example of cyclejs with firebase, and your driver is the only one using firebase v3 so it has been very useful.

Since my goal is to learn cyclejs and understand how (among other things) a driver works, I rewrote it in javascript, and along the way I made a few changes to your original design which I wanted to share with you. You can find [my driver here](https://github.com/vkammerer/cyclejs-firebase/blob/master/src/firebaseDriver.js).

If I understand correctly, it is for now necessary to listen to the "error" channel of your driver to perform write operations to the firebase service. While it is of course good practice to handle errors, it doesn't seem to be the responsibility of a driver to enforce it on users. Instead, we could use a [more general "response" channel](https://github.com/vkammerer/cyclejs-firebase/blob/master/src/firebaseDriver.js#L123-L128),  which would delegate the responsibility of handling success and error responses from firebase to an [outer defined function](https://github.com/vkammerer/cyclejs-firebase/blob/master/src/firebaseDriver.js#L34-L47).

One advantage of this approach is that it would match the API and formats of the official cyclejs/http driver: https://cycle.js.org/api/http.html, both for success and error handling.

What do you think about it?

I haven't used Typescript so far but I am interested in learning so if you think this API change is relevant I can open a PR.

**Comment by joshforisha** [comment]
Thanks for your interest in improving this library. I haven't used it in a while myself, but it does look like a handful of people are actively using it, so I'd love to enhance it in any way possible.

One of my annoyances with my first pass at this library is the error handling—it's kind of weird and isolated, but it was the easiest way to start off adapting Firebase v3, so I went with it. Having said that, it's currently _not_ actually necessary to pay any attention to the `error` stream itself for any Firebase operations. Write operations are done via passing an action to the Firebase sink. If you happen to care about errors (which you really probably should) then you'd listen to the `error` stream and do something with it. Otherwise, silent failure, I suppose.

Generally, there aren't responses directly from the Firebase driver. Changes in the structure are listened for using `get` and specified to paths. It's not clear to me how this method could be combined to include error handling, but maybe it is to others, or I'm just entirely delusional.

I definitely think closer to standard is better, and cycle/http is a great target, so I'm fully on-board for changes aiming at that. I'd welcome any PRs you'd like to submit. I'll examine possible improvements this weekend, too. In the meantime, let me know if you have any other questions/concerns about the mess I've made so far.

**Comment by vkammerer** [comment]
Thank you for the quick reply!

Your comment made me doubt about my first explanation, so I made a webpackbin using your driver to reproduce what I mean:
[webpackbin.com/bins/-KjyoWqwgVVStJVDQZRx](https://www.webpackbin.com/bins/-KjyoWqwgVVStJVDQZRx)

As you can see, if you comment out the subscription to the error channel, the push action is not performed anymore. This is because the execution of "[output$.addListener](https://github.com/joshforisha/cycle-firebase/blob/master/src/index.ts#L80)" is done only once the  "start" method of the error channel is executed, which happens only if the error channel is "subscribed to".

Or is there anything that I misunderstood in how to use the driver?

**Comment by joshforisha** [comment]
Well yep, you're right—likely my lack of expertise with `xstream`. I'll consider that a bug that I'll need to dig into (#2).

**Comment by joshforisha** [comment]
#2 is solved with the release of [`v1.0-rc.1`](https://github.com/joshforisha/cycle-firebase/releases/tag/v1.0-rc1), which is a redesign of the driver's API. I'd appreciate feedback on the changes if you have time, specifically if they solve the concerns you had originally.

**Comment by vkammerer** [comment]
Wow good work! And I see you keep pushing commits :)

Good job also on integrating the new shiny latest version of Firebase. I haven't checked it out so far but it looks more complete than before. And from what I've seen in the videos of the last Google IO, this is a technology Google is pushing so your driver should be useful.

Regarding your API: is there a reason why you do not imitate the API of the [official cyclejs http driver](https://cycle.js.org/api/http.html), which wraps both _success_ and _errors_ in a more general "response" source stream? Errors can then be handled by using "replaceError" as [explained here](https://cycle.js.org/api/http.html#cycle-http-error-handling)

Tell me if I'm wrong, but in your current implementation, it is not directly possible to know it a write operation to a Firebase db has been successful, which is to say, if the promise returned by the write operation _resolves_. It is of course possible to listen to a Firebase push notification about a ref, but that's a bit different.

**Comment by joshforisha** [comment]
I was attempting to adopt a structure closer to the main Firebase library, but thinking more about it, other than offering roughly similar semantics, that actually becomes fairly limiting within Cycle's flow. I'll try out a more `http` like structure to see if that's more versatile (it probably is) and whether that could offer a better way to continue forward with more tightly coupled calls I'm not covering yet (it probably will). Thanks for the thoughts.

**Comment by vkammerer** [comment]
Sounds good. One thing I wonder how to implement, is how to identify, in a "response" stream, the original write operation it refers to (be it a success or an error).
In the Cycle http driver, they have the `.select` API. Maybe something similar could be implemented in your driver?
In my first attempt here above, I was including the original action in the response stream, but there is probably a more elegant way.

**Comment by joshforisha** [comment]
I've put together an experimental `response-driven` branch: https://github.com/joshforisha/cycle-firebase/tree/response-driven that's hopefully a step in the right direction. Funnily enough, it's even closer to Firebase's library API, and offers a versatile action naming method (`.as(name)`) and source lookup (`responses(name)`).

**Comment by vkammerer** [comment]
That looks really good. I haven't tried it but if I understand correctly, we should now be able to write something like

```javascript
function main(sources) {
  const myGreatArticleResponse = sources.firebase.responses('myGreatArticle');
  // do something with the response, like update the UI, handle errors...
  const greatArticlePush = firebaseActions.database.ref('articles').push('great article').as('myGreatArticle');
  return {
    firebase: greatArticlePush
  }
}
```

What do you think about using the same vocabulary as for the http driver? As in, renaming "as" to "category", and "responses" to "select" ? That would make it really easy for any existing cyclejs user (who are probably already familiar with the http driver) to use this driver.

**Comment by joshforisha** [comment]
I considered `category` and `select` vs. `as` and `responses`, but felt like the more Firebase-focused terms made more sense here. `category` seems quite vague, and yet symbolic in a way that doesn't align with simply naming a request for reference, at least from a Firebase perspective. The calls are essentially already "categorized" to their containing APIs. `select` is similar—it's not immediately clear what is being selected, especially when the source contains multiple contexts (authentication methods, database lookups, etc.). So in my opinion, even though the paradigm of `@cycle/http` makes sense to model after, the actual exposed calls don't align all that closely with Firebase-centric functionality.

Of course, this is all my opinion. I'd love to hear other perspectives.

**Comment by vkammerer** [comment]
Yes indeed sounds good. I'm happy to use `.as` and `.responses` too :)

Looking forward to the release! I'll replace my driver in my apps.
