### ISSUE TITLE
Firebase and streams before and after log in

### ISSUE THREAD

**Issue by nkostop** [joshforisha/cycle-firebase#3]
Hello,
i want to use the firebase driver in a react native app. When the app opens up the user is not logged
in so firebase returns the Currently logged in user is null. Then all the sources.FIREBASE.get do not put a Listener and when the user finally logs in he is not seeing anything. If i close the app persisting the log in info in Async storage then when the app reopens again the sources.FIREBASE.get works right.
Is this a bug or is it something completely wrong with what am i doing?
thanks

**Comment by joshforisha** [comment]
Hi there. Sorry for the slow response.
Could you go into a little more detail about how you're using the driver with React? I haven't tried it, focusing on Cycle, but it should be possible with some manual bindings.

Off the top of my head, I'm not sure why you'd be seeing a non-updating auth state, but the broken sources might be related to #2, which is what I'm in the process of fixing by refactoring the exposed source object. I'll let you know when that's ready to test, hopefully fixing any issue you're seeing. In the meantime, I'm very interested to know more about your React-based setup.
